---
- name: Install vim
  yum: name=vim state=latest

- name: Install all the needed bits
  yum: pkg=libvorbis,yasm,freetype,zlib,bzip2,speex,libvpx,libogg,gcc,libvpx-devel state=latest

- name: write the script to build from source
  template: src=roles/avconf-converter/files/build-avconv.sh dest=/root/build-avconv.sh

- name: write the script to process images from s3
  template: src=roles/avconf-converter/templates/convert.sh.j2 dest=/root/convert.sh

- name: download av software
  get_url: url=http://libav.org/releases/libav-10.1.tar.gz dest=/root/libav-10.1.tar.gz mode=0440 force=no
  notify:
  - run build script